version: "3.8"
services:
  yaml-visualization:
    image: sakiphan/yaml-visualization:latest
    ports:
      - "5173:4173"
      - "3001:3001"
    environment:
      - VITE_CLAUDE_API_KEY=${VITE_CLAUDE_API_KEY}
    restart: unless-stopped